# DataSource Config
spring:
  datasource:
    driver-class-name: org.h2.Driver
    schema: classpath:db/tables.sql
    data: classpath:db/data.sql
    url: jdbc:h2:~/test
    username: sa
    password: